
const img=(name)=>'images/quiz/'+name;
const questions=[
{id:'project',title:'What are you designing?',hint:'Choose what you want Linva to help you create.',opts:[['home','Complete Home','A full-home interior journey',img('home-luxury.webp')],['living','Living Room','A welcoming living space',img('living-modern.webp')],['kitchen','Kitchen','Modular kitchen & storage',img('kitchen-warm.webp')],['bedroom','Bedroom','Bedroom, wardrobe & storage',img('bedroom-warm.webp')]]},
{id:'style',title:'Which home feels most like you?',hint:"Don't think about the names. Just choose the space you would love to come home to.",opts:[['modern','Modern & Minimal','Clean, calm and sophisticated',img('living-modern.webp')],['warm','Warm & Elegant','Wood, soft lighting and warm neutrals',img('bedroom-warm.webp')],['luxury','Luxury & Glamorous','Statement finishes and dramatic details',img('home-luxury.webp')],['indian','Indian Contemporary','Modern comfort with Indian character',img('living-modern.webp')]]},
{id:'colour',title:'Which colour world feels right for you?',hint:'Imagine these colours across your walls, furniture and décor.',opts:[['neutral','Warm Neutrals','Ivory, beige, sand and walnut',img('bedroom-warm.webp')],['airy','Light & Airy','White, cream and light wood',img('living-modern.webp')],['earthy','Earthy & Natural','Olive, terracotta, brown and wood',img('home-luxury.webp')],['bold','Bold & Dramatic','Charcoal, deep tones and brass',img('home-luxury.webp')]]},
{id:'ambience',title:'How should your home feel?',hint:'Think about the feeling you want when you walk through the door.',opts:[['calm','Calm & Peaceful','Soft, relaxed and uncluttered',img('bedroom-warm.webp')],['premium','Luxurious & Premium','Elegant, refined and impressive',img('home-luxury.webp')],['warm','Warm & Welcoming','Cosy, comfortable and family-friendly',img('living-modern.webp')],['expressive','Stylish & Expressive','Personal, artistic and distinctive',img('living-modern.webp')]]},
{id:'kitchen',title:'Which kitchen would you choose?',hint:'Look at the overall feel, not just the cabinet colour.',opts:[['sleek','Sleek & Minimal','Clean lines and concealed storage',img('kitchen-warm.webp')],['wood','Warm Wood','Natural textures and warm finishes',img('kitchen-warm.webp')],['premium','Premium & Bold','Stone, dark finishes and statement details',img('home-luxury.webp')],['bright','Bright & Practical','Light, functional and easy to maintain',img('kitchen-warm.webp')]]},
{id:'colourRisk',title:'How adventurous are you with colour?',hint:'There is no right answer — this helps your designer understand your comfort zone.',opts:[['timeless','Keep it timeless','I prefer colours that stay classic',img('living-modern.webp')],['accent','A little colour','Mostly neutral with selected accents',img('home-luxury.webp')],['personality','Give me personality','I enjoy colour, art and character',img('living-modern.webp')],['bold','Go bold','I love dramatic colour choices',img('home-luxury.webp')]]},
{id:'priority',title:'What matters most in your home?',hint:'If you had to prioritise one, what would it be?',opts:[['storage','Maximum Storage','Everything should have its place',img('kitchen-warm.webp')],['beauty','Beautiful Design','I want the home to make an impression',img('home-luxury.webp')],['comfort','Family Comfort','It must work beautifully every day',img('living-modern.webp')],['maintenance','Easy Maintenance','Beautiful, practical and easy to live with',img('kitchen-warm.webp')]]},
{id:'vastu',title:'Would you like Vastu considered?',hint:'We ask because it can influence layout decisions. Choose what suits you.',opts:[['important','Very Important','Plan the design around Vastu',img('home-luxury.webp')],['some','Somewhat Important','Consider it where practical',img('living-modern.webp')],['no','Not Important','Design and functionality come first',img('living-modern.webp')],['guidance','I’d Like Guidance','Discuss it with my designer',img('home-luxury.webp')]]},
{id:'finish',title:'Which finish attracts you more?',hint:'Choose the material personality you naturally prefer.',opts:[['wood','Natural Wood & Texture','Warm, tactile and organic',img('kitchen-warm.webp')],['stone','Stone / Marble Luxury','Elegant, refined and premium',img('home-luxury.webp')],['matte','Matte & Minimal','Quiet, clean and contemporary',img('living-modern.webp')],['gloss','Glossy & Statement','Reflective, bold and eye-catching',img('home-luxury.webp')]]},
{id:'custom',title:'How personalised should your home be?',hint:'Tell us how much creative freedom you want your designer to have.',opts:[['simple','Keep it simple','Smart and practical',img('living-modern.webp')],['personal','Make it personal','I want it to reflect me',img('bedroom-warm.webp')],['unique','Make it unique',"I don't want a typical home",img('home-luxury.webp')],['designer','Surprise me','Give me the designer’s best idea',img('living-modern.webp')]]},
{id:'budget',title:'What investment range are you considering?',hint:'A rough range helps us recommend the right approach. You can choose “Not sure”.',opts:[['under5','Under ₹5 lakh','',img('kitchen-warm.webp')],['5to10','₹5–10 lakh','',img('living-modern.webp')],['10to15','₹10–15 lakh','',img('home-luxury.webp')],['15to25','₹15–25 lakh','',img('home-luxury.webp')],['25to40','₹25–40 lakh','',img('home-luxury.webp')],['40plus','₹40 lakh+','',img('home-luxury.webp')],['unsure','I’m not sure yet','Let’s discuss it',img('living-modern.webp')]]},
{id:'timeline',title:'When are you planning to start?',hint:'This helps our team understand how soon we should contact you.',opts:[['now','Immediately','I’m actively looking',img('home-luxury.webp')],['1to3','Within 1–3 months','',img('living-modern.webp')],['3to6','Within 3–6 months','',img('bedroom-warm.webp')],['exploring','Just exploring','I’m researching ideas',img('living-modern.webp')]]}
];
let i=0, answers={}, lead={};
const $=id=>document.getElementById(id);
function relevant(q){if(!answers.project)return true; if(q.id==='kitchen' && answers.project!=='kitchen' && answers.project!=='home')return false; if(q.id==='vastu' && answers.project==='office')return false; return true}
function activeQuestions(){return questions.filter(relevant)}
function render(){const qs=activeQuestions(); if(i>=qs.length){finish();return} const q=qs[i]; $('stepLabel').textContent='Question '+(i+1);$('stepCount').textContent=(i+1)+' / '+qs.length;$('progress').style.width=((i+1)/qs.length*100)+'%';$('qTitle').textContent=q.title;$('qHint').textContent=q.hint;$('eyebrow').textContent='DESIGN DISCOVERY';$('options').className='options count-'+q.opts.length;$('options').innerHTML=q.opts.map(o=>`<button class="option ${answers[q.id]===o[0]?'selected':''}" data-v="${o[0]}"><span class="check">✓</span><img src="${o[3]}" alt="${o[1]} interior reference" loading="lazy"><div class="copy"><strong>${o[1]}</strong>${o[2]?'<span>'+o[2]+'</span>':''}</div></button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{answers[q.id]=b.dataset.v;document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('next').disabled=false;$('next').style.opacity=1});$('next').disabled=!answers[q.id];$('next').style.opacity=answers[q.id]?1:.55}
$('start').onclick=()=>{const n=$('leadName').value.trim(),raw=$('leadPhone').value.replace(/\D/g,'');let p=raw;if(p.length===12&&p.startsWith('91'))p=p.slice(2);const repeated=/^(\d)\1{9}$/.test(p);const sequential=/^(0123456789|1234567890|9876543210)$/.test(p);if(n.length<2){$('startError').textContent='Please enter your name.';return}if(!/^[6-9]\d{9}$/.test(p)||repeated||sequential){$('startError').textContent='Please enter a valid Indian WhatsApp number.';return}lead={name:n,phone:p};$('startError').textContent='';$('intro').classList.add('hidden');$('quiz').classList.remove('hidden');render()};
$('next').onclick=()=>{const qs=activeQuestions(),q=qs[i];if(!answers[q.id])return;i++;render()};
$('skip').onclick=()=>{const qs=activeQuestions(),q=qs[i];delete answers[q.id];i++;render()};
function finish(){ $('quiz').classList.add('hidden');$('result').classList.remove('hidden'); const style=answers.style==='luxury'?'Modern Luxury':answers.style==='indian'?'Indian Contemporary':answers.style==='warm'?'Warm Modern':'Modern Minimal';$('resultTitle').textContent=style;$('resultText').textContent='Your choices suggest a '+style.toLowerCase()+' direction with a clear preference for thoughtful, personalised spaces. Your Linva designer can use these preferences as a starting point for your consultation.';const labels={project:'Project',style:'Style',colour:'Colour',ambience:'Ambience',kitchen:'Kitchen',colourRisk:'Colour Confidence',priority:'Priority',vastu:'Vastu',finish:'Finish',custom:'Customisation',budget:'Budget',timeline:'Timeline'};const val={};activeQuestions().forEach(q=>{const o=q.opts.find(x=>x[0]===answers[q.id]);if(o)val[q.id]=o[1]});$('profile').innerHTML=Object.entries(labels).filter(([k])=>val[k]).map(([k,l])=>`<div><small>${l}</small><b>${val[k]}</b></div>`).join('');const msg=encodeURIComponent(`Hi Linva Interiors, I completed the Design Discovery Quiz. My name is ${lead.name}. My design profile is ${style}. I would like to discuss my interior project.`);$('wa').href='https://wa.me/918961698488?text='+msg;try{localStorage.setItem('linva_quiz_lead',JSON.stringify({lead,answers,profile:val,completedAt:new Date().toISOString()}))}catch(e){}}
$('restart').onclick=()=>{i=0;answers={};lead={};$('result').classList.add('hidden');$('intro').classList.remove('hidden');$('startError').textContent='';$('leadPhone').value='';$('leadName').focus();};
$('leadPhone').addEventListener('input',()=>{$('leadPhone').value=$('leadPhone').value.replace(/\D/g,'').slice(0,10)});
$('leadName').addEventListener('keydown',e=>{if(e.key==='Enter'){$('leadPhone').focus()}});
$('leadPhone').addEventListener('keydown',e=>{if(e.key==='Enter')$('start').click()});
